### ISSUE TITLE
Add simple UI

### ISSUE THREAD

**Issue by Fylipp** [Fylipp/shortcut-swap#5]
- [ ] Create prototype without interacting with the core logic (tracked by #7)
- [ ] Extract core logic into its own library (tracked by #6)
- [ ] Implement core logic in UI app using the extracted library (tracked by #5)

**Comment by AndreasHae** [comment]
- [ ] Create prototype without interacting with the core logic (tracked by #7)
- [ ] Extract core logic into its own library (tracked by #6)
- [ ] Implement core logic in UI app using the extracted library
